`default_nettype none

// On-chip boot ROM - IMEM 0x0000-0x007F (128 bytes, but only the first
// 88 are real content; the rest default to 0x00, which decodes as NOP
// at the high byte and part of a following NOP at the low byte -
// harmless padding, never actually reached since the bootloader jumps
// away well before address 0x58 in every code path).
//
// Content is generated by build_boot_rom.py (see that file's docstring
// for the wire protocol) - boot_rom_body.vh is its direct output,
// included verbatim below. Regenerate that file and re-copy it here if
// the bootloader routine changes; don't hand-edit the case statement.
//
// Same imem-style 1-cycle-latency port convention as every other
// memory front-end in this design (ram32.v, qspi_shared_engine.v).
// Always present, always readable - this is what makes address 0x0000
// (the CPU's reset vector) valid with or without the QSPI Pmod
// connected, which is the whole point of this module existing.

module boot_rom (
    input  wire       clk,
    input  wire       rst_n,

    input  wire [6:0] addr,
    input  wire       valid,

    output reg  [7:0] rdata,
    output reg        ready
);

    reg [7:0] data;

    always @(*) begin
        case (addr)
`include "boot_rom_body.vh"
            default: data = 8'h00;
        endcase
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            ready <= 1'b0;
            rdata <= 8'h00;
        end else begin
            ready <= valid;
            if (valid)
                rdata <= data;
        end
    end

endmodule
